### ISSUE TITLE
imagebox

### ISSUE THREAD

**Issue by PedroAlvesq** [NeoforceControls/XNA#12]
how put my imagebox to accept 3d models

**Comment by Cyral** [comment]
Check out Matt Betcher's Video: https://www.youtube.com/watch?v=tY9MMX2yTEY

He includes code on how he did this.

**Comment by PedroAlvesq** [comment]
thanks but the link of he give don´t work anymore

**Comment by Cyral** [comment]
Oh I see :/

Well I'm assuming you could create a render target, draw your models, then create a `Texture2D` from the target and set it as your image.

**Comment by PedroAlvesq** [comment]
but i need a 3d model and not a 2d model

**Comment by Cyral** [comment]
You can render your models to a rendertarget, and transform the target into a 2D texture, it will show your 3D model as a texture.
http://www.riemers.net/eng/Tutorials/XNA/Csharp/Series3/Render_to_texture.php

**Comment by PedroAlvesq** [comment]
ok
but is not i want but i gonna try
I want to show a 3d and not 2d textute
but thanks for the help

**Comment by Cyral** [comment]
Yes, but if you draw a "3D" model, what is it on your screen? It is 2D on your screen, but because of shading and perspective it looks 3D.

You can draw your 3D model to a `RenderTarget`, and cast your `RenderTarget` to a `Texture2D`, now does this mean it doesn't look 3D? No, it still has perspective and everything, you just now have it in a texture that you can set to your image.

This is exactly how I believe it is done in the video I posted above.

He is not actually drawing a 3D model in the window, he is drawing it to a `RenderTarget` (Seen in the background, can be removed), then making a texture from the rendertarget, and then setting an `ImageBox` within the form to the texture, each frame.

**Comment by Grimston** [comment]
As this is not really an issue with the library I will close this one.

Summary
Question: Draw a Model to the image box
Solution: Draw to a `RenderTarget`, then set the `ImageBox` texture to the `RenderTarget`
