### ISSUE TITLE
Button Not Fired When Clicked

### ISSUE THREAD

**Issue by mikrokode** [NeoforceControls/XNA#31]
Recently I have downloaded this control to be used in my own development project. I am facing a probelm, the control could not be fired when clicking on it, may I know what is the reason?

**Comment by Grimston** [comment]
Could you provide an example of what is not working?

If you subscribe to the `Click` event you should be fine as long as you are updating the Manager.

```CSHARP
Button btn = new Button(_manager);
btn.Init();
btn.Parent = this;
btn.Click += new EventHandler(btn_Click);

void btn_Click(object sender, EventArgs e)
{
      Window.Title = "Button Clicked";    
}
```

I would also suggest you move to using MonoGame instead of XNA, as it's still developed and supports multiple platforms. (We also have a port of Neoforce Controls to MonoGame available here https://github.com/NeoforceControls/Neoforce-Mono )

**Comment by Grimston** [comment]
Closed due to no response.
