### ISSUE TITLE
MonoGame support

### ISSUE THREAD

**Issue by romanov** [NeoforceControls/XNA#6]
Any plans?

**Comment by Grimston** [comment]
At the moment no, I have tried a small test and encountered loads of issues. 

There are also a few technical issues with mono game.
1. No hardware mouse support
2. In complete Graphics API, (reset)

Issues I had where. Rectangles would not accept parent information.  And is seriously offset and the controls failed to move there parent rectangle. 
Constant control flickering.

Back buffer displays since reset is not implemented. 

Plans would end up being rewrite the xna version. Remove hardware cursor for a software cursor.

Remove the application class. To keep things prepared for the push to monogame.

And then move from there.

At the moment i have too much going on to do this.
If anyone is interested in starting this feel free.

**Comment by PedroAlvesq** [comment]
any advences about porting for monogame

**Comment by lucid2310** [comment]
I am curious, what advantage does monogame have over XNA in terms of the framework, I have been using XNA to create my game and havent found any issues yet. But I am still early in the development cycle.

**Comment by Grimston** [comment]
@Kammikazy At the moment, nothing, MonoGame has improved the content pipeline support to almost near completion. I just don't have the time at the moment to give another go at porting it.

@lucid2310 MonoGame supports more platforms, and uses OpenGL instead of DirectX, the advantage is, MonoGame is in active development, while XNA has been dumped by Microsoft.

XNA is good for Windows/Xbox.
MonoGame Windows/Windows8(Metro)/Xbox/Linux/Mac/Android/IOS and so on.

**Comment by Grimston** [comment]
Basic port is working and is available here: https://github.com/NeoforceControls/Neoforce-Mono

Currently Windows Only, need to replace all the native methods still, but It works in a Windows OpenGL MonoGame project

**Comment by Cyral** [comment]
Nice Grimston, I was hoping this would come! Might make me come back to XNA if NeoForce can work with Monogame.

**Comment by PedroAlvesq** [comment]
great to use the neoforce in monogame is the same away is use in xna

**Comment by Grimston** [comment]
The only thing missing is the Application class. This is because its not cross platform.

Also you will notice the cursor is software based now. Currently still using native win32 functions for that to load the current skins cursor files.

Oh and copy paste is disabled for now.
